# Generated by Django 5.2.5 on 2025-08-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdrf', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Restaurant_type',
            field=models.CharField(choices=[('in', 'indian'), ('CH', 'chines'), ('IT', 'italian'), ('MA', 'maxican'), ('GR', 'greek'), ('FF', 'fast food'), ('OT', 'other')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
