# Generated by Django 5.2.5 on 2025-08-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdrf', '0009_restaurant_restaurant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Datetime', models.DateTimeField()),
                ('Restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstdrf.restaurant')),
            ],
        ),
    ]
