# Generated by Django 5.2.5 on 2025-08-29 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdrf', '0010_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rating', to='firstdrf.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Restaurant_type',
            field=models.CharField(choices=[('IN', 'indian'), ('CH', 'chines'), ('IT', 'italian'), ('MA', 'maxican'), ('GR', 'greek'), ('FF', 'fast food'), ('OT', 'other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sales', to='firstdrf.restaurant'),
        ),
    ]
