# Generated by Django 5.2.5 on 2025-08-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdrf', '0011_alter_rating_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
