# Generated by Django 5.2.5 on 2025-08-29 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdrf', '0012_alter_restaurant_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rating', to='firstdrf.restaurant', unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sales', to='firstdrf.restaurant', unique=True),
        ),
    ]
